package com.example.liaoshouwang.dbdemo.greendaodb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.liaoshouwang.dbdemo.greendaodb.GreenUser;

import com.example.liaoshouwang.dbdemo.greendaodb.GreenUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenUserDaoConfig;

    private final GreenUserDao greenUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenUserDaoConfig = daoConfigMap.get(GreenUserDao.class).clone();
        greenUserDaoConfig.initIdentityScope(type);

        greenUserDao = new GreenUserDao(greenUserDaoConfig, this);

        registerDao(GreenUser.class, greenUserDao);
    }
    
    public void clear() {
        greenUserDaoConfig.clearIdentityScope();
    }

    public GreenUserDao getGreenUserDao() {
        return greenUserDao;
    }

}
